version: '3'
services:
  oracle-async:
    platform: linux/amd64
    build:
      context: .
    environment:
      TZ: America/Chicago
      ORACLE_LOWERCASE: 'true'
    depends_on:
      - oracle
  oracle:
    platform: linux/amd64
    image: gvenzl/oracle-xe:11-slim
    environment:
      TZ: America/Los_Angeles
      ORACLE_PASSWORD: oracle
